services:
  cloudflared:
    image: cloudflare/cloudflared:2026.6.1
    network_mode: bridge
    command:
      - tunnel
      - --no-autoupdate
      - --no-prechecks
      - --protocol
      - http2
      - --edge-ip-version
      - "4"
      - --url
      - http://host.docker.internal:8080
    dns:
      - 1.1.1.1
      - 8.8.8.8
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
